"""Added unique constraint for station_id and date in temperature_records table

Revision ID: 3eccbcb93127
Revises: 69a0b5c3028c
Create Date: 2024-07-06 14:53:06.270461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eccbcb93127'
down_revision = '69a0b5c3028c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperature_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('tmax', sa.Float(), nullable=True),
    sa.Column('tmin', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'date', name='_station_date_uc')
    )
    op.drop_table('temperature_record')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperature_record',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('tmax', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tmin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], name='temperature_record_station_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='temperature_record_pkey')
    )
    op.drop_table('temperature_records')
    # ### end Alembic commands ###
